version: '3.9'

services:
  app:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - 'DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}'
      - 'DJANGO_ZARINPAL_MERCHANT_ID=${DOCKER_COMPOSE_DJANGO_ZARINPAL_MERCHANT_ID}'
    #      - 'DJANGO_DEBUG=True'
    ports:
      - 8000:8000

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
