# Generated by Django 4.0.2 on 2023-04-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_authority_order_zarinpal_authority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zarinpal_authority',
            new_name='zibal_trackId',
        ),
    ]
