# Generated by Django 4.0.2 on 2023-01-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Prefect')], max_length=10),
        ),
    ]
