# Generated by Django 4.0.2 on 2023-02-07 17:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_alter_comments_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment author'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Prefect')], max_length=10, verbose_name='Point'),
        ),
    ]
